services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules # Exclut le node_modules local
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=127.0.0.1
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
    #   - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:password@database:5432/blablabook

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blablabook
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - /app/node_modules

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
